
import java.util.LinkedList;
import java.util.ListIterator;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/*
 * Drop student from the university
 * @author cjoyner
 */
public class DropAStudentFromTheUniversityAdmin extends javax.swing.JFrame {

    /**
     * Creates new form DropAStudentFromTheUniversityAdmin
     */
    public DropAStudentFromTheUniversityAdmin(LinkedList<Student> student, LinkedList<CurrentCourse> course) {
        initComponents();
        setDefaultCloseOperation(HIDE_ON_CLOSE);
        studentList = student;
        listCourse = course;
        reset();
    }
    /**
     * add students from student list to select list box
     */
    private void reset()
    {
        DefaultListModel<Student> listModel = new DefaultListModel();
        ListIterator<Student> iterator = studentList.listIterator();
        //set student into list model
        while (iterator.hasNext())
        {
            Student student = iterator.next();
            listModel.addElement(student);
        }
        
        selectList.setModel(listModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        selectList = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        dropList = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        drop = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        clear = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selectList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                selectListMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(selectList);

        jLabel3.setText("Select a Student to Drop");

        jScrollPane2.setViewportView(dropList);

        jLabel4.setText("Drop Students");

        drop.setText("Drop");
        drop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        clear.setText("Clear");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(drop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(drop)
                        .addGap(18, 18, 18)
                        .addComponent(clear)
                        .addGap(16, 16, 16)
                        .addComponent(exit))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(21, 21, 21)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Mouse is released selected student is add to drop list box
     * @param evt 
     */
    private void selectListMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectListMouseReleased
        //get index of click object
        int index = selectList.getSelectedIndex();
         //check index
        if (index != -1)
        {
            ListModel<Student> listModel = selectList.getModel();
            //get student
            Student student = listModel.getElementAt(index);
            DefaultListModel<Student> dropListModel = new DefaultListModel();
            listModel = dropList.getModel();
            //adds items already in dropList to dropListModel
            for (int a = 0; a < listModel.getSize(); a++){
                dropListModel.addElement(listModel.getElementAt(a));
            }
            //add student to dropList
            dropListModel.addElement(student);
            dropList.setModel(dropListModel);
        }
    }//GEN-LAST:event_selectListMouseReleased

    /**
     * Uses a button to drop students from student list
     * @param evt 
     */
    private void dropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropActionPerformed
        ListModel<Student> listModel = dropList.getModel();
        //drops students in dropList box
        for (int a  = 0; a < listModel.getSize(); a++)
        {
            //get student
            Student student = listModel.getElementAt(a);
            ListIterator<CurrentCourse> iterator = student.getCurrentSchudule().listIterator();
            //drop student from enrolled courses
            while (iterator.hasNext())
            {
                CurrentCourse course = iterator.next();
                course.getEnrolledStudents().remove(student);
                course.dropStudent();
            }
            //drop student from student list
            studentList.remove(student);
            
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, student.getFirstName()+ " " + student.getLastName() + " has been removed." );
            
            Backup backup = new Backup();
            backup.backupCourses(listCourse);
            backup.backupStudents(studentList);
        }
    }//GEN-LAST:event_dropActionPerformed

    /**
     * Clears all list boxes, calls reset
     * @param evt 
     */
    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        DefaultListModel listModel = new DefaultListModel();
        listModel.clear();
        dropList.setModel(listModel);
        selectList.setModel(listModel);
        reset();
    }//GEN-LAST:event_clearActionPerformed

    /**
     * Exits drop a student from the university
     * @param evt 
     */
    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_exitActionPerformed

    private LinkedList<CurrentCourse> listCourse;
    private LinkedList<Student> studentList;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clear;
    private javax.swing.JButton drop;
    private javax.swing.JList dropList;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList selectList;
    // End of variables declaration//GEN-END:variables
}
