
import java.util.LinkedList;
import java.util.ListIterator;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.ListModel;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * Allows an Admin to drop a student from a course or courses
 */
public class DropAStudentAdmin extends javax.swing.JFrame {

    /**
     * Creates new form DropAStudentAdmin
     */
    public DropAStudentAdmin(LinkedList<Student> student) {
        initComponents();
        studentList = student;
        reset();
    }
    
    
    private void reset()
    {
        ListIterator<Student> iterator = studentList.listIterator();
        DefaultListModel listModel = new DefaultListModel();
        //add students to the list model
        while (iterator.hasNext())
        {
            Student element = iterator.next();
            listModel.addElement(element);
        }
        //set list of students
        selectList.setModel(listModel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        selectList = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        courseList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        drop = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        dropList = new javax.swing.JList();
        jLabel3 = new javax.swing.JLabel();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        selectList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                selectListMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(selectList);

        courseList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                courseListMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(courseList);

        jLabel1.setText("Select Students to Drop");

        jLabel2.setText("Select Course to Drop");

        drop.setText("Drop");
        drop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropActionPerformed(evt);
            }
        });

        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(dropList);

        jLabel3.setText("Drop Course");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(drop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(drop)
                        .addGap(18, 18, 18)
                        .addComponent(exit)))
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dropActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropActionPerformed
         ListModel<Course> listModel = dropList.getModel();
         ListModel<Student> listModel2 = selectList.getModel();
         //get student
         int index = selectList.getSelectedIndex();
         Student student = listModel2.getElementAt(index);
        //remove select course in dropList
        for (int a = 0; a < listModel.getSize(); a++)
        {
            Course course = listModel.getElementAt(a);
            boolean remove = student.getCurrentSchudule().remove(course);
            //removes course credits from approved credits
            if (remove)
            {
                student.setCreditHoursEnrolled(student.getCreditHoursEnrolled() - course.getCredits());
                //drop student from course
                course.getEnrolledStudents().remove(student);            
                course.dropStudent();
            }
            
            //display remove course
            JFrame frame = new JFrame();
            JOptionPane.showMessageDialog(frame, "Course " + course.getName() + " has been removed." );
        }
        
        reset();
    }//GEN-LAST:event_dropActionPerformed

    private void selectListMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_selectListMouseReleased
        //get index of click object
        int index = selectList.getSelectedIndex();
        ListModel<Student> list = selectList.getModel();
        //get student
        Student student = list.getElementAt(index);
        DefaultListModel listModel = new DefaultListModel();
        //get course list for student
        ListIterator<Course> iterator = student.getCurrentSchudule().listIterator();
        
        //adds student's course to list model
        while (iterator.hasNext())
        {
            Course element = iterator.next();
            listModel.addElement(element);
        }
        //set the list
        courseList.setModel(listModel);
    }//GEN-LAST:event_selectListMouseReleased

    private void courseListMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_courseListMouseReleased
        //get index of click object
        int index = courseList.getSelectedIndex();
        ListModel<Course> listModel = courseList.getModel();
        //get course
        Course course = listModel.getElementAt(index);
        DefaultListModel dropListModel = new DefaultListModel();
        listModel = dropList.getModel();
        //adds items already in addCourseList to addListModel
        for (int a = 0; a < listModel.getSize(); a++){
            dropListModel.addElement(listModel.getElementAt(a));
        }
        //add course to addCourseList
        dropListModel.addElement(course);
        dropList.setModel(dropListModel);
    }//GEN-LAST:event_courseListMouseReleased

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_exitActionPerformed

    private LinkedList<Student> studentList;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList courseList;
    private javax.swing.JButton drop;
    private javax.swing.JList dropList;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList selectList;
    // End of variables declaration//GEN-END:variables
}
